-- 1. Create custom Type
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- 2. Create Tables
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHAR(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price DECIMAL(9, 2) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT inventory_pk PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) 
        REFERENCES public.classification (classification_id)
);

CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type public.account_type DEFAULT 'Client'::public.account_type,
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

-- 3. Populate Data (Examples)
INSERT INTO public.classification (classification_name) VALUES ('Sport'), ('SUV'), ('Truck');
-- [Add your full inventory insert statements here from your activity]

-- 4. FINAL QUERIES FROM TASK 1 (Required by assignment)
-- Update Hummer description
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update all Image paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
